
###############################################################################
# Task b: FPb_buildDict.py (Section 4.2) (15%)
################
#
# Implement the body of this script:
#
#	Build a dictionary for this corpus using "sentences.txt" generated by FPa_prepTrans.sh
#
#	You must NOT use/import	any other modules, apart from "sys"
#
#	Refer to Section 4.2 in "../LING402_FP.pdf" for other requirements
#
###############################################################################

import sys

if not len(sys.argv) == 3:
    raise SystemExit("Usage: {} file_sentences file_dict".format(sys.argv[0]))



### INSERT YOUR CODE BELOW THIS LINE ###

infile = sys.argv[1]
outfile = sys.argv[2]

#infile = './resources/sentences.txt'
#outfile = './etc/dict.txt'


text = open(infile, "r")
  
d = dict()
  
for line in text:
    line = line.strip()
    line = line[8:]
    words = line.split(" ")
  
    for word in words:
        if word in d:
            d[word] = d[word] + 1
        else:
            d[word] = 1
  
with open(outfile, "a") as myfile:
    for w in sorted(d, key=d.get, reverse=True):
        towrite = w + '\t' + str(d[w]) + '\n'
        myfile.write(towrite)
